---
- name: Dependencies
  apt: name={{ item }} state=present
  with_items:
      - git
      - curl
      - build-essential
      - libssl-dev

- name: Download nvm install script
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh dest=/tmp/install.sh

- name: Execute nvm install script
  shell: bash install.sh chdir=/tmp

- name: Install the specified node version
  shell: export NVM_DIR="{{ home }}/.nvm" && . {{ home }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm run {{ node_version }} --version && nvm alias default {{ node_version }} creates={{ home }}/.nvm/versions/node/v{{ node_version }}
